name: Testing

on:
- push
- pull_request

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version:
        - stable
        platform:
        - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Test
      run: go test ./... -v -cover -race
